ModeleDB/ModeleDB/Models/ErrorViewModel.cs
using System;

namespace ModeleDB.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ModeleDB/ModeleDB/Models/ModeleModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ModeleDB.Models
{
    public class ModeleModel
    {
        public int ID { get; set; }
        public string Name { get; set; }

        public string Scale { get; set; }

        public string Brand { get; set; }

        public string Details { get; set; }
    }
}

ModeleDB/ModeleDB/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ModeleDB.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ModeleDB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ModeleDB/ModeleDB/Controllers/ModeleController.cs
using Microsoft.AspNetCore.Mvc;
using ModeleDB.Logic;
using ModeleDB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ModeleDB.Controllers
{
    public class ModeleController : Controller
    {
        ModeleManager modeleManager = new ModeleManager();
        public IActionResult Index()
        {
            var modelList = modeleManager.GetModels();
            return View(modelList);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(ModeleModel modeleModel)
        {
            modeleManager.AddModel(modeleModel);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Remove(int id)
        {
            var model = modeleManager.GetModel(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult RemoveConfirm(int id)
        {
            modeleManager.RemoveModel(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = modeleManager.GetModel(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(ModeleModel model)
        {
            modeleManager.UpdateModel(model);
            return RedirectToAction("Index");
        }
    }
}

ModeleDB/ModeleDB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ModeleDB/ModeleDB/Views/Modele/Add.cshtml
@model ModeleDB.Models.ModeleModel

@{
    ViewData["Title"] = "Add";
}

<h1>Add new scale model</h1>

@*<h4>ModeleModel</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="input-group" style="padding-bottom:15px;">
                <label asp-for="Name" class="control-label input-group-text"></label>
                <div>                    
                    <input asp-for="Name" class="form-control" />
                </div>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="input-group" style="padding-bottom:15px;">
                    <label asp-for="Scale" class="control-label input-group-text"></label>
                    <div><input asp-for="Scale" class="form-control" /></div>
                    <span asp-validation-for="Scale" class="text-danger"></span>
                </div>
                <div class="input-group" style="padding-bottom:15px;">
                    <label asp-for="Brand" class="control-label input-group-text"></label>
                    <div><input asp-for="Brand" class="form-control" /></div>
                    <span asp-validation-for="Brand" class="text-danger"></span>
                </div>
                <div class="input-group" style="padding-bottom:15px;">
                    <label asp-for="Details" class="control-label input-group-text"></label>
                    <div><input asp-for="Details" class="form-control" /></div>
                    <span asp-validation-for="Details" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
</form>
    </div>
</div>

<div >
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ModeleDB/ModeleDB/Views/Modele/Edit.cshtml
@model ModeleDB.Models.ModeleModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ModeleModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Scale" class="control-label"></label>
                <input asp-for="Scale" class="form-control" />
                <span asp-validation-for="Scale" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details" class="control-label"></label>
                <input asp-for="Details" class="form-control" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ModeleDB/ModeleDB/Views/Modele/Index.cshtml
@model IEnumerable<ModeleDB.Models.ModeleModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Main Page</h1>

<p>
    <a class="btn btn-outline-success btn-lg" asp-action="Add">Add new scale model to database</a>
</p>
<table class="table table-hover table-dark">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Scale)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Brand)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Details)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Scale)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brand)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Details)
            </td>
            <td class="nav-item dropdown">
                <a class="nav-link dropdown-toggle btn btn-dark" data-toggle="dropdown" href="#" role="button" aria-expanded="false">Options</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item " asp-action="Edit" asp-route-id="@item.ID">Edit</a> 
                    <a class="dropdown-item " asp-action="Remove" asp-route-id="@item.ID">Remove</a> 
                </div>
            </td>
            @*<td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Remove" asp-route-id="@item.ID">Usuń</a> |               
            </td>*@
        </tr>
}
    </tbody>
</table>

ModeleDB/ModeleDB/Views/Modele/Remove.cshtml
@model ModeleDB.Models.ModeleModel

@{
    ViewData["Title"] = "Remove";
}

<h1>Remove</h1>

<div>
        <h4>Scale model from database</h4>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2 badge badge-pill badge-secondary" style="margin-bottom:5px;">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class = "col-sm-2 badge badge-pill badge-secondary" style="margin-bottom: 5px;">
                @Html.DisplayNameFor(model => model.Scale)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Scale)
            </dd>
            <dt class = "col-sm-2 badge badge-pill badge-secondary" style="margin-bottom: 5px;">
                @Html.DisplayNameFor(model => model.Brand)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Brand)
            </dd>
            <dt class = "col-sm-2 badge badge-pill badge-secondary" style="margin-bottom: 5px;">
                @Html.DisplayNameFor(model => model.Details)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Details)
            </dd>
        </dl>
    </div>
    <div>
         <form asp-action="RemoveConfirm" methos="post">
            <input type="hidden" asp-for="ID"/>
            <input type="submit" value="Deletion confirm" class="btn btn-danger" />
        </form>

        <a class="btn btn-info" asp-action="Index">Back to main page</a>
    </div>

ModeleDB/ModeleDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ModeleDB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header style="margin-bottom: 100px;">
    <div class="fixed-top">
        <div class="collapse" id="navbarToggleExternalContent">
            <div class="bg-dark p-4">   
                <h5 class="text-white h4">Navigation</h5>
                    <nav>
                        <a class="btn btn-secondary btn-lg btn-block" asp-area="" asp-controller="Modele" asp-action="Index">Model Home</a>
                    </nav>
                    <nav>
                        <a class="btn btn-secondary btn-lg btn-block" asp-area="" asp-controller="Modele" asp-action="Add">Model Add</a>
                    </nav>                
            </div>
        </div>
        <nav class="navbar navbar-dark bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>
    </div>
    </header>
    @*<header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ModeleDB</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Modele" asp-action="Index">Model Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Modele" asp-action="Add">Dodaj Model</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ModeleDB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>